# Normal Classification
dataset:
  budget: 60
  classifier_fitting_mode: from_scratch
  initial_points_per_class: 30
  classifier_batch_size: 32
  validation_split: 0.2

classifier:
  type: NSF
  hidden: [64, 128]

optimizer:
  type: NAdam
  lr: 0.001
  weight_decay: 0.0

