# Normal Classification
dataset:
  budget: 800
  classifier_fitting_mode: finetuning
  initial_points_per_class: 200
  classifier_batch_size: 64
  validation_split: 0.2

classifier:
  type: Gauss
  dropout: 0.0121342046294311
  hidden: [32, 64, 128]

optimizer:
  type: NAdam
  lr: 0.000381943576138542
  weight_decay: 0.00513161888918376

